<?php

namespace Arca\CompanyBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends EntityRepository
{
    public function searchIndex(string $search)
    {
        $result = $this->createQueryBuilder("c")
            ->join('c.categories', 'cat')
            ->andWhere('c.title LIKE :title OR c.address LIKE :address OR c.postalcode LIKE :postalcode OR c.city LIKE :city OR cat.title LIKE :cat')
            ->setParameter('title', '%'.$search.'%')
            ->setParameter('address', '%'.$search.'%')
            ->setParameter('city', '%'.$search.'%')
            ->setParameter('postalcode', '%'.$search.'%')
            ->setParameter('cat', '%'.$search.'%')
            ->getQuery()
            ->execute();

        return $result;
    }

}
