<?php

namespace Arca\CategoryBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCategoriesForm()
    {
        return $this->createQueryBuilder('c')
            ->orderBy('title');
    }
}
